require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'ConstruyaalCosto' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'toolbar-android', :path => '../node_modules/@react-native-community/toolbar-android'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'react-native-viewpager', :path => '../node_modules/@react-native-community/viewpager'

  pod 'RNSharedElement', :path => '../node_modules/react-native-shared-element'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  pod 'RNBottomActionSheet', :path => '../node_modules/react-native-bottom-action-sheet'

  pod 'react-native-cookies', :path => '../node_modules/@react-native-community/cookies'

  target 'ConstruyaalCostoTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'ConstruyaalCosto-tvOS' do
  # Pods for ConstruyaalCosto-tvOS

  target 'ConstruyaalCosto-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
